### ISSUE TITLE
Not returning any RD results. 

### ISSUE THREAD

**Issue by Trizzel19** [Goldenfreddy0703/repository.otaku.testing#6]
Hiya! I'd like to start by saying, thank you for all your hard work! 
I swapped over to the testing version of otaku at your suggestion. 
I've enabled the scrapping settings and it seems to only be returning embed results when trying to watch something. 
I'm running on a firestick with kodi omega.

**Comment by joezito129** [comment]
i think golenfreddy messed up something you can test out my version on my repo. it is not listed as testing so i would replace your otaku version

**Comment by joezito129** [comment]
i just tested it on his version and it seem to work for me could you send me you log and make sure you have enable scrape for uncached sources

**Comment by Trizzel19** [comment]
No error logs are flagging, so if there's a way to pull a log to send over you'll have to advise on how to do it. (I'm relatively new to this) 
I have noticed when scrapping for results it's only displaying embed sites to pull from and not torrent sites like nyaa etc. 
I've got uncached sources enabled, I've checked that torrent sources are enabled. (That's default though. I've not got the verizon option of nyaa enabled since I'm not a verizon user) 
Fen light is working, so it isn't an issue there.

**Comment by Trizzel19** [comment]
I've seen there's an issue raised on the other testing repo. Just to add onto that: it isn't showing my username for RD within the settings but when I check my devices on RD it's authorised and showing last seen. So if it could be related. 
If there's a way for me to get a log over, advise and I'll do so in the morning. It's 2am here haha

**Comment by Trizzel19** [comment]
Here's the log. This is after trying to find results aswell:

https://paste.kodi.tv/edapuxayuz

**Comment by Trizzel19** [comment]
So I did a fresh install, went back through everything and it's working now. 
Not sure why that was the case, but way up.
